# Generated by Django 2.2.12 on 2020-05-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200522_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bfhghg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hghghg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hghghghgh',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nbnbnb',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
