# Generated by Django 2.2.12 on 2020-05-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200522_1337"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="hghghg",),
    ]
