# Generated by Django 2.2.12 on 2020-05-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_customtext_hghghg"),
    ]

    operations = [
        migrations.RemoveField(model_name="homepage", name="dsfwgrf",),
    ]
