# Generated by Django 2.2.12 on 2020-05-22 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_remove_homepage_dsfwgrf"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="hghghg",),
    ]
