# Generated by Django 2.2.12 on 2020-05-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_remove_customtext_hghghg"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="gghghghg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="hyghghg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jhjhjh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="jhjhjhjhjh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="mhjhjhjh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customtext",
            name="vbfgfgfgf",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
