# Generated by Django 2.2.12 on 2020-05-22 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_auto_20200522_1402"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="gghghghg",),
        migrations.RemoveField(model_name="customtext", name="hyghghg",),
        migrations.RemoveField(model_name="customtext", name="jhjhjhjhjh",),
        migrations.RemoveField(model_name="customtext", name="mhjhjhjh",),
        migrations.RemoveField(model_name="customtext", name="title",),
        migrations.RemoveField(model_name="customtext", name="vbfgfgfgf",),
    ]
