# Generated by Django 2.2.12 on 2020-05-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200522_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='customtext',
            name='ghhgfmhg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='hgkhgj',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customtext',
            name='ukgkjhkjhg',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
